### ISSUE TITLE
Question about HTTP headers

### ISSUE THREAD

**Issue by Malvoz** [hteumeuleu/email-guidelines#1]
In my experience, when sending emails (in PHP), at least some email clients seem to expect the presence (or perhaps the absence even) of certain HTTP headers, or header-value pairs, otherwise the email might get filtered as spam.

Is this something you're aware of? I see no mentions of it in the documentation so it might be a nice addition. Here's an article mentioning this: https://www.formget.com/how-to-stop-email-spam/

<hr>

Aside, do you have intentions of continuing to working on https://github.com/W3CGHtmail?

**Comment by hteumeuleu** [comment]
Hello,

You're right that certain email headers like `DKIM` help to fight against spam filters. However, I feel like this is more a job on the side of the code you use to send your email, not the code you use to build your actual HTML email. So I don't feel this should be part of my email coding guidelines.

Regarding @W3CGHtmail, I'd definitely love to continue. But I haven't found the right way and right time to start this the proper way. Another current project I'm working on, [caniemail](https://github.com/hteumeuleu/caniemail), will definitely help build the path for a better understanding of the current support of HTML and CSS in email clients, and so will hopefully let me work on standard specifications afterwards. Just don't expect anything from me regarding W3CGHtmail before  late 2020/2021.
